# Generated by Django 5.2 on 2025-04-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=90)),
                ('email', models.TextField(blank=True, null=True)),
                ('expirience', models.TextField(max_length=255)),
                ('data_field', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
